version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bugsbunny-db
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: bugsbunny
    ports:
      - "5432:5432"
    volumes:
      - bugsbunny_data:/var/lib/postgresql/data

volumes:
  bugsbunny_data:
